# Generated by Django 6.0.7 on 2026-07-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_address_order_city_order_mobile_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivary'), ('Delivered', 'Delivered')], default='Ordered', max_length=30),
        ),
    ]
